export enum Icons {
  logo = "/icons/logo.png",
  harmony = "/icons/harmony.png",
  axieSold = "/icons/axie-sold.png",
  totalSale = "/icons/totalSale.png",
  arrowLeft = "/icons/arrowLeft.png",
  menu = "/icons/menu.png",
  dashboard = "/icons/dashboard.png",
  marketplace = "/icons/marketplace.png",
  marketplaceWhite = "/icons/marketplace-white.png",
  heart = "/icons/hearts.png",
  dagger = "/icons/plain-dagger.png",
  earth = "/icons/earth.png",
  chevronRight = "/icons/chevronRight.svg",
  chevronDown = "/icons/chevronDown.svg",
  upArrow = "/icons/upArrow.png",
  exclamation = "/icons/exclamation.svg",
  eyeShow = "/icons/Eye-show.svg",
  eyeHide = "/icons/Eye-hide.svg",
  id = "/icons/id.png",
  settings = "/icons/settings.png",
  inventory = "/icons/inventory.png",
  edit = "/icons/edit.png",
}
